name: Execute dhall-docs
description: Generate documentation for Dhall packages
author: Nikita Volkov
branding:
  icon: book-open
  color: blue
inputs:
  input:
    description: Path to source directory
    required: false
    default: .
  package-name:
    description: Package name
    required: false
outputs:
  path:
    description: Path to the generated documentation directory
runs:
  using: docker
  image: docker://ghcr.io/nikita-volkov/dhall-docs.github-action:69d17586dd4227cbea4f87765ab24237c499f36d
  env:
    input: ${{ inputs.input }}
    package_name: ${{ inputs.package-name }}
