name: Build

on:
  push:
    branches: [ master, main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: docker
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update action.yml
        uses: fjogeleit/yaml-update-action@v0.16.1
        with:
          valueFile: action.yml
          propertyPath: runs.image
          value: docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          updateFile: true
          commitChange: false

      - name: Commit updated action.yml
        id: update-image-ref
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Update docker image ref to ${{ github.sha }}
          file_pattern: action.yml
