name: Release

on:
  push:
    branches:
      - major
      - minor
      - patch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: docker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update action.yml
        uses: fjogeleit/yaml-update-action@v0.13.2
        with:
          valueFile: action.yml
          propertyPath: runs.image
          value: docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          updateFile: true
          commitChange: false

      - name: Commit updated action.yml
        id: update-image-ref
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update docker image ref to ${{ github.sha }}
          file_pattern: action.yml

      - name: Bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          release_branches: major,minor,patch
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.ref_name }}
          commit_sha: ${{ steps.update-image-ref.outputs.commit_hash }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ steps.update-image-ref.outputs.commit_hash }}
          tag: ${{ steps.tag.outputs.new_tag }}
          generateReleaseNotes: true
          makeLatest: true

      - name: Merge to master
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: ${{ github.ref_name }}
          target_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
