on:
  push:
    branches:
      - major
      - minor
      - patch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: docker
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update action.yml
        uses: fjogeleit/yaml-update-action@v0.12.3
        with:
          valueFile: action.yml
          propertyPath: runs.image
          value: docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          updateFile: true
          commitChange: false

      - id: update-image-ref
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update docker image ref
          file_pattern: action.yml

      - id: tag
        name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          release_branches: major,minor,patch
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.ref_name }}
          commit_sha: ${{ steps.update-image-ref.outputs.commit_hash }}

      - name: Release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.ref_name }}
          tag: ${{ steps.tag.outputs.new_tag }}

      - name: Merge to master
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: ${{ github.ref_name }}
          target_branch: master
          github_token: ${{ github.token }}
